# docker-compose.yml avec montages locaux pour Git
version: "3"

services:
  # PostgreSQL database avec données stockées localement
  postgres:
    image: postgres:14-alpine
    container_name: chirpstack_postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=chirpstack
      - POSTGRES_DB=chirpstack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chirpstack"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis database
  redis:
    image: redis:7-alpine
    container_name: chirpstack_redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MQTT broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: chirpstack_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "5",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChirpStack
  chirpstack:
    image: chirpstack/chirpstack:4
    container_name: chirpstack
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./chirpstack:/etc/chirpstack
      - ./data/lorawan-devices:/opt/chirpstack/lorawan-devices
    command: --config /etc/chirpstack
    environment:
      # Variables d'environnement pour dépannage - utiles pour priorité sur le fichier de config
      - POSTGRESQL__DSN=postgres://chirpstack:password@postgres/chirpstack?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - MQTT__SERVER=tcp://mosquitto:1883
      - INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=chirpstack/events/{{.ApplicationID}}/{{.DeviceInfo.DevEUI}}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=chirpstack/commands/{{.ApplicationID}}/{{.DeviceInfo.DevEUI}}
