version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: example_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      INFLUXDB_DB: example_db
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8088:8088/udp"
    networks:
      - backend

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - backend
    depends_on:
      - influxdb
      - mariadb

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - influxdb

volumes:
  mariadb_data:
  influxdb_data:
  telegraf_config:
  grafana_data:

networks:
  backend:
    driver: bridge
